/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Bat.glb -T 
Files: Bat.glb [231.48KB] > F:\My Documents\Sites\games\jungle-vines\public\models\Bat-transformed.glb [81.88KB] (65%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelBat(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/Bat-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log("actions", actions)
    actions["BatArmature|Bat_Flying"].play()
    // return () => actions[name].fadeOut(0.5)
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Bat" position={[0, 2.436, 0.129]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="Bat_1" geometry={nodes.Bat_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bat_1.skeleton} />
          <skinnedMesh name="Bat_2" geometry={nodes.Bat_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bat_2.skeleton} />
          <skinnedMesh name="Bat_3" geometry={nodes.Bat_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bat_3.skeleton} />
          <skinnedMesh name="Bat_4" geometry={nodes.Bat_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bat_4.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/Bat-transformed.glb')
