/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Crocodile.glb -T 
Files: Crocodile.glb [107.48KB] > F:\My Documents\Sites\games\jungle-vines\public\models\Crocodile-transformed.glb [10.27KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCrocodile(props) {
  const { nodes, materials } = useGLTF('models/Crocodile-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Plane-Mesh'].geometry} material={materials['4CAF50']} />
      <mesh geometry={nodes['Plane-Mesh_1'].geometry} material={materials['8BC34A']} />
      <mesh geometry={nodes['Plane-Mesh_2'].geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes['Plane-Mesh_3'].geometry} material={materials.FFFFFF} />
    </group>
  )
}

useGLTF.preload('models/Crocodile-transformed.glb')
