/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelFly(props) {
  const { nodes, materials } = useGLTF('models/Fly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle004_Circle001-Mesh'].geometry}
        material={materials['455A64']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle004_Circle001-Mesh_1'].geometry}
        material={materials['80DEEA']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle004_Circle001-Mesh_2'].geometry}
        material={materials.F44336}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle004_Circle001-Mesh_3'].geometry}
        material={materials['4CAF50']}
      />
    </group>
  )
}

useGLTF.preload('models/Fly.glb')
