/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 models\Piranha.glb --output output\Piranha.js --transform --keepnames --shadows 
Files: models\Piranha.glb [154.09KB] > F:\My Documents\Articles Media\AMCOT\Models\Quaternius\Fishing\JSX\output\Piranha-transformed.glb [37.56KB] (76%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Quaternius/Fishing/Piranha.glb`

export function ModelQuaterniusFishingPiranha(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(link)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Fish_Armature">
          <primitive object={nodes.Main1} />
        </group>
        <group name="Piranha">
          <skinnedMesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube040.skeleton} />
          <skinnedMesh name="Cube040_1" geometry={nodes.Cube040_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube040_1.skeleton} />
          <skinnedMesh name="Cube040_2" geometry={nodes.Cube040_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube040_2.skeleton} />
          <skinnedMesh name="Cube040_3" geometry={nodes.Cube040_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube040_3.skeleton} />
          <skinnedMesh name="Cube040_4" geometry={nodes.Cube040_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube040_4.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(link)
