/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useGraph } from '@react-three/fiber'

export function ModelSpider(props) {
    const group = useRef()

    const {
        // nodes, 
        scene,
        materials,
        animations
    } = useGLTF('models/Spider-transformed.glb')

    const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
    // useGraph creates two flat object collections for nodes and materials
    const { nodes } = useGraph(clone)

    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        // console.log("actions", actions)
        actions["SpiderArmature|Spider_Walk"].play()
        // return () => actions[name].fadeOut(0.5)
    }, [])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Root_Scene">
                <primitive object={nodes.Root} />
                <group name="Cube" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <skinnedMesh
                        name="Cube_1"
                        geometry={nodes.Cube_1.geometry}
                        material={materials.Material}
                        skeleton={nodes.Cube_1.skeleton}
                    />
                    <skinnedMesh
                        name="Cube_2"
                        geometry={nodes.Cube_2.geometry}
                        material={materials['Material.001']}
                        skeleton={nodes.Cube_2.skeleton}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('models/Spider-transformed.glb')
